export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';
export const FACEBOOK_LOGIN_FAIL = 'FACEBOOK_LOGIN_FAIL';
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const SAVE_EVENT = 'SAVE_EVENT';
export const DELETE_SAVED_EVENTS = 'DELETE_SAVED_EVENTS';